### ISSUE TITLE
[FEAT] Modify BadgeView

### ISSUE THREAD

**Issue by hekang42** [42Caterpie/Lets-Git-It-iOS#16]
## 📌  Feature Issue
BadgeView 만들기

## 📝  To-do

- [x] badge asset 추가
- [x] badge별 달성 상황 UserDefaults에 저장.
- [x] 달성 한 badge는 caption과 함께 컬러로 표시.
