### ISSUE TITLE
[FEAT] Login 화면 만들기 with github

### ISSUE THREAD

**Issue by hekang42** [42Caterpie/Lets-Git-It-iOS#21]
## 📌  Feature Issue

Login 화면 만들기

## 📝  To-do

- [x] 로그인 화면 만들기
- [x] github login 연동
- [x] login 후 User data 전달
- [x] 자동 로그인, 로그아웃
- [x] 로그인 시 progressView 띄우기
