### ISSUE TITLE
[FEAT] iOS 13 화면 및 기능 수정

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/Lets-Git-It-iOS#26]
## 📌  Feature Issue
iOS13 기기에서 정상적으로 작동되지 않는 화면 및 기능 수정

## 📝  To-do

- [x] LaunchScreen
- [ ] 텍스트필드 클릭시 카드 찌그러지는 현상(ignoreSafeArea)
- [ ] 루트 뷰에서만 내비게이션 바 가리기
- [ ] login시 progress view 꺼지지 않는 현상
- [ ] notification date picker
- [ ] color theme image
- [ ] text label sizes
