### ISSUE TITLE
[FEAT] NameCard View 구현

### ISSUE THREAD

**Issue by hekang42** [42Caterpie/Lets-Git-It-iOS#4]
## 📌  Feature Issue
Git Profile, Streak, Today's Commit 정보를 나타내는 뷰를 구현.

## 📝  To-do

- [x] Get Profile Image in user's github -> image
- [x] Get Git streak in user's github -> Int
- [x] Get today's git contribution -> Bool
