### ISSUE TITLE
[FEAT] 챌린지 카드 화면 기능 추가

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/Lets-Git-It-iOS#5]
## 📌  Feature Issue
챌린지 카드 화면 디자인 속성 재설정, streak 불러와서 뷰에 표시하는 모델 생성

## 📝  To-do
- [x] TextField의 속성 설정(디자인, 제약조건)
- [x] TextField의 기능 추가(내용 저장 등)
- [x] streak 데이터 모델 생성, 뷰와 연결
