### ISSUE TITLE
[FEAT] 뷰 세부 설정 변경

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/Lets-Git-It-iOS#50]
## 📌  Feature Issue
뷰 세부 설정 변경

## 📝  To-do

- [x] 런치스크린 이미지
- [x] 영어로 모두 바꾸기
- [x] 카드 라벨 간격 조정
- [x] refresh Button 기능 추가
