### ISSUE TITLE
[Fix] 버전 관리 및 위젯 미리보기 색상

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/Lets-Git-It-iOS#84]
## 🐞 버그 설명
- Build Version 수정 안 됨
- Appstore 버전 제대로 가져오지 못하는 현상
- 작은 사이즈 위젯 미리보기 색상 green으로 고정

## 📝 todo
- [x] Build Version을 1.2.1 -> 2.0으로 맞추기
- [x] appstore lookup api url을 http -> https로 변경
- [x] 작은 사이즈 위젯 미리보기 색상을 Userdefault에 맞춤
