### ISSUE TITLE
[FEAT] 뷰 크기 비율 상수 추가, 챌린지 카드 뷰 크기 변경

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/Lets-Git-It-iOS#9]
## 📌  Feature Issue
- 디자인된 뷰 크기 비율로 계산 후 Constants에 추가
- 챌린지 카드 뷰 크기 비율에 따라 바뀌게 변경
- iOS14 이상부터 키보드 팝업시 뷰 찌그러지는 현상 해결

## 📝  To-do
- [x]  iOS14 이상부터 키보드 팝업시 뷰 찌그러지는 현상 해결
- [x]  디자인된 뷰 크기 비율로 계산 후 Constants에 추가
- [x] 챌린지 카드 뷰 비율에 따라 바뀌게 변경
